# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: 'Default'
  demands:
  - agent.name -equals Deepaks-MacBook-Pro

stages:
  - stage: Maven
    jobs:
      - job: Maven
        steps:
        - task: Maven@3
          inputs:
              mavenPomFile: 'pom.xml'
              mavenOptions: '-Xmx3072m'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: 'default'
              jdkArchitectureOption: x64
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              goals: 'package'

  - stage: SAST
    jobs:
      - job: SAST
        steps:
        - task: SnykSecurityScan@1
          inputs:
            serviceConnectionEndpoint: 'Deepak Lohar'
            testType: 'code'
            failOnIssues: true

