# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: 'Default'
  demands:
  - agent.name -equals Deepaks-MacBook-Pro

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: 'default'
    jdkArchitectureOption: 'ARM64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Deepak Lohar'
    testType: 'code'
    failOnIssues: true
  
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Deepak Lohar'
    testType: 'container'
    dockerImageName: 'deepaklohar/hellocd:1.0.0'
    dockerfilePath: 'Dockerfile'
    monitorWhen: 'always'
    failOnIssues: true